# What is NumPy?

1.NumPy is a python library used for working with arrays.

2.NumPy stands for Numerical Python.

3.NumPy aims to provide an array object that is up to 50x faster that traditional Python lists.

4.The array object in NumPy is called ndarray

# How to install NumPy????

In [1]:
!pip install numpy

In [3]:
import numpy as np

# How to import NumPy???

In [4]:
a = numpy.array([1, 2, 3, 4, 5])

print(a)


[1 2 3 4 5]


In [5]:
type(a)

numpy.ndarray

# You can do this code like this

In [ ]:

import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a)

# What is ndarray??

In [ ]:
type(a)

1.NumPy is used to work with arrays. The array object in NumPy is called ndarray.

2.We can create a NumPy ndarray object by using the array() function.we can pass list,tuple as an argument to array()

In [ ]:
#Tuple as argument

In [ ]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr) 

In [ ]:
type(arr)

# We can create multidimentinal Arrays

In [1]:
import numpy as np
c = np.array([[1, 2, 3], [4, 5, 6],[5,9,0]])


In [7]:
print(c)

[[1 2 3]
 [4 5 6]
 [5 9 0]]


# how to know dimension???

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [2]:
print(c.ndim)

2


# How to access element from an Array???

You can access an array element by referring to its index number.

In [9]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [5, 9, 0]])

In [11]:
c[0][2]


3

In [12]:
c[1][1]

5

In [13]:
c[-1][-2]

9

In [14]:
c[-2][-2]

5

In [15]:
for x in c:
    print(x)

[1 2 3]
[4 5 6]
[5 9 0]


# Numpy Vs Lists

The operations such as data storing, indexing and iterating are similar both in list and numpy.

However, Numpy uses less memory, is faster, and more convenient than Lists. 

We cannot perform calculations (add, subtract, multiply, divide and exponentiation) on Python Lists but we can on Numpy Arrays.


In [16]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
type(my_matrix)

list

In [17]:
my_matrix+my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
import numpy as np
ar=np.array(my_matrix)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
ar*ar

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [22]:
p_list = [4,5,6,7]
print(p_list)
print(p_list*3)

[4, 5, 6, 7]
[4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7]


In [23]:
pr=np.array(p_list)

In [24]:
pr*3

array([12, 15, 18, 21])

# Negative Indexing???

In [11]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)

print('Last element from 2nd dim: ', arr[-1, -1]) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10


# Slicing???

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:7:2])

[2 4 6]


In [27]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
print(arr[1, 1:4]) 

[7 8 9]


In [29]:
arr[1,0:3]

array([6, 7, 8])

In [30]:
arr.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

# NumPy Array Copy vs View

In [32]:
import numpy as np

k=np.array([3,4,5,6,8])

l=k.copy()



In [34]:
k[2]=9

In [35]:
k

array([3, 4, 9, 6, 8])

In [36]:
l

array([3, 4, 5, 6, 8])

In [37]:
import numpy as np

k=np.array([3,4,5,6,8])

l=k.view()



In [38]:
k[2]=10

In [39]:
k

array([ 3,  4, 10,  6,  8])

In [40]:
l

array([ 3,  4, 10,  6,  8])

# shape  Vs Reshape

The shape of an array is the number of elements in each dimension.

Reshaping arrays :Reshaping means changing the shape of an array.

In [41]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) 

(2, 4)


In [28]:
k=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [29]:
print(k.shape)

(12,)


In [43]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# zeros and ones
Generate arrays of zeros or ones

In [44]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# How can we join two arrays???

In [36]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


# hstack Vs vstack 

In [37]:
a=np.array([21,32,45])
b=np.array([98,23,34])

In [38]:
s=np.hstack((a,b))

In [39]:
print(s)

[21 32 45 98 23 34]


In [42]:
s=np.vstack((a,b))

In [44]:
print(s)
s.ndim

[[21 32 45]
 [98 23 34]]


2

# How can i split an Array???

In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


# Searching Arrays

In [51]:
import numpy as np

arr = np.array([1, 2, 3,4, 5, 4, 4])

x = np.where(arr == 2)

print(x) 

(array([1], dtype=int64),)


# Sorting an Array

In [52]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr)) 

[0 1 2 3]


In [53]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [54]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr)) 

[[2 3 4]
 [0 1 5]]


# Random number Generation

In [62]:
from numpy import random

x = random.randint(1000)

print(x) 

415


In [64]:
from numpy import random

x = random.rand()

print(x) 

0.4059534693323663


In [65]:
from numpy import random

x=random.randint(1000, size=(8))

print(x) 

[911   5 788 991 206 930 946  14]


# Broadcasting

In [83]:
my_array=np.array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
my_array[1:7:2]=22

In [85]:
my_array

array([ 0, 22,  2, 22,  4, 22,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# The End..